---
title: Fuel Prices in Auckland
subtitle: STATS 220 Semester One, 2026
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
```

```{css}

body {
  background: linear-gradient(to bottom, #ccffcc, #ffffff);
  font-family: "Helvetica Neue", sans-serif;
  color: #333;
  padding: 20px;
}

h1 {
  color: #ffffff;
  font-family: "Georgia", serif;
  font-weight: bold;
  text-align: center;
  background-color: #99cc00;
  padding: 15px;
  border-radius: 15px;
}

h2 {
  color: #ffffff;
  font-family: "Georgia", serif;
  font-weight: bold;
  background-color: #ccff00;
  padding: 10px;
  border-radius: 12px;
}

h3 {
  color: #99cc00;
  font-family: "Georgia", serif;
  font-weight: bold;
}

p {
  color: #444;
  font-size: 18px;
  line-height: 1.6;
}

li {
  font-size: 18px;
}

img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  border-radius: 15px;
  box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
  margin-top: 15px;
  margin-bottom: 20px;
}

.section {
  background-color: #ffffffcc;
  padding: 15px;
  border-radius: 15px;
  margin-bottom: 20px;
}
```

# Summary

```{r}
library("tidyverse")

csv_file <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vTElqKsgASNluXUaano0vLYorvYaBtoDSF2gCqncpWcQAzg2BnE7kft1m-gm_eIMdFa0fGTrocxx_Ou/pub?output=csv"

logged_data <- read_csv(csv_file)

logged_data <- logged_data %>%
  rename(
    `Date` = `Enter the date`,
    `Time` = `Enter the time`,
    `Fuel Brand` = `Select the fuel station brand`,
    `Location` = `Where is the fuel station located? Only enter the suburb/town/district.`
  )

# Location and Time data #

logged_data$`Location`

logged_data %>%
  ggplot(aes(x = `Location`)) +
  geom_bar() +
  theme_minimal()

# Unleaded 91 data

unleaded_91 <- logged_data$`Unleaded 91`
average_91 <- sum(unleaded_91) / length(unleaded_91)
average_91 <- round(average_91, 2)

# bar graph of Unleaded 91 prices
logged_data %>%
  ggplot(aes(x = `Unleaded 91`)) +
  geom_bar(fill = "darkolivegreen") +
  theme_minimal()


```

